### ISSUE TITLE
Rule34.xxx option is not working

### ISSUE THREAD

**Issue by LunaTheBronyGamer** [asadahimeka/booruwf-web#1]
if you click on it,it basically doesn't load any images at all no matter what tag i put in

**Comment by asadahimeka** [comment]
There are many restrictions using APIs on cross-origin sites. It may be that rule34.xxx has banned my website or server ip. 
It's recommended to use [Tampermonkey ](https://www.tampermonkey.net/) extension with my userscript. install: [https://greasyfork.org/en/scripts/444885](https://greasyfork.org/en/scripts/444885)

**Comment by asadahimeka** [comment]
@LunaTheBronyGamer , When I try to request the rule34.xxx API, it returns a captcha for human-machine verification. So I can't fix this problem for now. You can use the userscript mentioned above to continue browsing rule34.

![image](https://user-images.githubusercontent.com/31837214/198663841-1ab3263b-5691-4961-bbc0-be597725570d.png)
