### ISSUE TITLE
大佬泥嚎，之前WEB用的十分顺手，现在好像停掉了，只有油猴脚本在~本人纯小白

### ISSUE THREAD

**Issue by a7k7k567** [asadahimeka/booruwf-web#3]
大佬泥嚎，之前WEB用的十分顺手，现在好像停掉了，只有油猴脚本在~现在要搭建一个类似的东西应该怎么做呢？
油猴脚本本身就是注入JS吧？那直接建立一个带有该JS不用安装脚本的网页应该怎么做呢？请指导我.jpg
o(╥﹏╥)o

没有图片反代也无所谓……只是要在不安装油猴的情况下运行脚本（浏览器不支持插件的情况下）也要使用的……所以就像自己搞搞看，弄个带有这个脚本的网页，但奈何不懂代码……完全搞不定（服务器我想办法自己找找……）

**Comment by asadahimeka** [comment]
挂 🪜 后可以看

**Comment by a7k7k567** [comment]
谢谢大佬Thanks♪(･ω･)ﾉ
能用了~
